### ISSUE TITLE
themeing harmony todo-list

### ISSUE THREAD

**Issue by Gankra** [axodotdev/axomdbook#3]
Here's things I didn't bother themeing/harmonizing when i quickly hacked this up, and ostensibly should get a proper pass (fine if the answer is "what we have now is fine", should still validate that):

* [ ] main content
  * [ ] code-blocks / inline-code
  * [ ] tables
  * [ ] lists
  * [ ] --fg (main text color)
  * [ ] misc padding/spacing
* [ ] chrome
  * [ ] search bar
  * [ ] theme selector menu
  * [ ] header/footer/sidebar bg-color/separator
